version: 2
jobs:
  deploy_master:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: install firebase-tools
          command: sudo npm install -g firebase-tools
      - run:
          name: build project app
          command: npm run --prefix app build:prod
      - run:
          name: build project web
          command: npm run --prefix web build:prod
      - run:
          name: Deploy Firebase Hosting
          command: firebase deploy --token $FIREBASE_CI_TOKEN --project $PROD_PROJECT_ID

  deploy_dev:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: install node_modules
          command: npm install --prefix app & npm install --prefix web
      - run:
          name: install firebase-tools
          command: sudo npm install -g firebase-tools dotenv
      - run:
          name: build project app
          command: npm run --prefix app build:dev
      - run:
          name: build project web
          command: npm run --prefix web build:dev
      - run:
          name: Deploy Firebase Hosting
          command: firebase deploy --token $FIREBASE_CI_TOKEN --project $DEV_PROJECT_ID

workflows:
  version: 2
  build_and_deploy: # ワークフローの名前
    jobs:
      - deploy_dev: # 上で定義したジョブを指定します
          filters:
            branches:
              only: master # developブランチのみを実行対象とします
      - deploy_master:
          filters:
            branches:
              only: prod # masterブランチのみを実行対象とします
